# Generated by Django 5.1.1 on 2024-10-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Collection',
            new_name='collection',
        ),
    ]
